### PR TITLE
Created it-it.yml

### PR DESCRIPTION
**Pull request by iVillager**
Added italian language with love <3

### CODE REVIEW

**Comment by Nuytemans-Dieter** [comment]
Hey! Thanks for your contribution!
I'd like to request a change, files have a naming format so `it-it.yml` should be `it_IT.yml` (the underscore and capital letters matter). Otherwise the plugin will fail to find this file. 

We also have an italian translation already but perhaps you could use your file to improve our current translation?
Thank you for your addition!

**Comment by iVillager** [comment]
> Hey! Thanks for your contribution!
> I'd like to request a change, files have a naming format so `it-it.yml` should be `it_IT.yml` (the underscore and capital letters matter). Otherwise the plugin will fail to find this file.
> 
> We also have an italian translation already but perhaps you could use your file to improve our current translation?
> Thank you for your addition!

Yeah you could use my file ofc! 
I renamed the file to the correct format

**Comment by Nuytemans-Dieter** [comment]
> > Hey! Thanks for your contribution!
> > I'd like to request a change, files have a naming format so `it-it.yml` should be `it_IT.yml` (the underscore and capital letters matter). Otherwise the plugin will fail to find this file.
> > We also have an italian translation already but perhaps you could use your file to improve our current translation?
> > Thank you for your addition!
> 
> Yeah you could use my file ofc!
> I renamed the file to the correct format

Thank you for your contribution! Looks good to me. I'll merge once the build status is okay!

**Comment by Nuytemans-Dieter** [comment]
Well the build failed but this has nothing to do with this PR. Merging anyway.
Thanks for the improvements!!

**Pull request merged**
