### PR TITLE
Added new Placeholder!

### PR DESCRIPTION
**Pull request by abhiram555**
New placeholder for placeholder api :)

### CODE REVIEW

**Comment by abhiram555** [comment]
Commit name : Add files via upload

**Comment by abhiram555** [comment]
I would like to make more placeholders its  3 am for me I will do tomorrow!

**Comment by abhiram555** [comment]
if  you want merge this! :)

**Comment by Nuytemans-Dieter** [comment]
That would be awesome, thank you.
PlaceholderAPI is currently not being used for BetterSleeping but it's a planned feature (#77 and  #114). The PAPI extension class is a remainder of v2 with the intent to bring it back which is why the code is still there.

Regardless, it'd be nice to support it once again. I'll review this in a few moments.

Thanks :)

**Comment by abhiram555** [comment]
Okey!

**Comment by Nuytemans-Dieter** [comment]
Hey again!

 I noticed that you placed `public ConfigLib sleeping` in the main class. I prefer to use private variables when possible to prevent problems in the future when maintaining the code. You could pass it as an argument in the constructor of the PAPI expansion class if needed (or even the percentage/absolute amount as an argument).

You could also use [SleepStatus](https://github.com/Nuytemans-Dieter/BetterSleeping/blob/c8d3c93e1c82bafa56a3c2cbaa0bc845b1821e60/src/main/java/be/dezijwegel/bettersleeping/util/SleepStatus.java) when looking for certain stats. To get an instance of this, you can use `bedEventHandler.getSleepStatus(World world)` which is available in the plugins's main class.

Please try not to move files around too much, they should at the very least remain in the `src/main/java/be/dezijwegel/bettersleeping` folder so we can be sure that they will be included when building a jar.

I thank you for your contribution but I hope you understand I cannot merge this PR just yet (until these few issues are sorted out).

**Comment by abhiram555** [comment]
Hmm i will fix all tommarow and add more 
Placeholders....

**Comment by Nuytemans-Dieter** [comment]
That's be awesome! Thank you so much.

**Comment by abhiram555** [comment]
Hey i fixed everything check new 2 commits

**Pull request merged**
